# Generated by Django 4.1.4 on 2022-12-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpw',
            name='type',
            field=models.CharField(choices=[('confidential', 'confidential'), ('sharable', 'sharable')], max_length=12),
        ),
    ]
